/**
 * A2Z COMPUTERS — Desktop PCs Catalog Data Store
 * Structured inventory for New & Refurbished Desktop Towers, Gaming Rigs, and Workstations.
 * Shared across desktops.html and desktop-details.html.
 */

const DESKTOP_DATA = [
  // =========================================================================
  // 1. NEW DESKTOP COMPUTERS
  // =========================================================================
  {
    id: 'a2z-titan-forge-rtx4080',
    type: 'new',
    brand: 'Custom A2Z',
    model: 'A2Z Titan-Forge Studio RTX 4080 Super',
    tagline: 'Flagship Creator & AI Workstation with 360mm AIO Liquid Cooling',
    category: 'Custom-Built Workstation',
    processor: 'Intel Core i9-14900K (24-Core, up to 6.0GHz)',
    ram: '64GB DDR5 6000MHz RGB',
    storage: '2TB PCIe 4.0 NVMe SSD + 4TB Enterprise HDD',
    graphics: 'NVIDIA GeForce RTX 4080 Super 16GB GDDR6X',
    price: 264990,
    priceDisplay: '₹2,64,990',
    availability: 'In Stock (Built to Order)',
    badge: 'Flagship Rig',
    image: 'assets/products/desktop-custom.jpg',
    gallery: [
      'assets/products/desktop-custom.jpg',
      'assets/products/desktop-gaming.jpg',
      'assets/products/desktop-tower.jpg'
    ],
    shortSpecs: 'Core i9-14900K • 64GB DDR5 • 2TB NVMe • RTX 4080 Super 16GB • 360mm AIO Liquid',
    fullSpecs: {
      processor: 'Intel Core i9-14900K (24 Cores, 32 Threads, 36MB Smart Cache, up to 6.0 GHz Turbo)',
      ram: '64GB (2x32GB) Corsair Vengeance RGB DDR5 6000MHz CL30 (Dual Channel, Expandable to 192GB)',
      storage: '2TB Samsung 990 PRO Gen4 M.2 NVMe SSD (7450 MB/s Read) + 4TB Seagate IronWolf 7200RPM',
      graphics: 'ASUS TUF Gaming GeForce RTX 4080 Super 16GB GDDR6X with DLSS 3.5 & Frame Gen',
      motherboard: 'ASUS ROG STRIX Z790-E Gaming WiFi II (PCIe 5.0, Wi-Fi 7, 5x M.2 Slots)',
      powerSupply: 'Corsair RM1000e 1000W 80 PLUS Gold ATX 3.0 Fully Modular PSU with 12VHPWR Cable',
      coolingChassis: 'Lian Li O11 Dynamic EVO RGB Glass Chassis + NZXT Kraken 360mm RGB AIO Liquid Cooler',
      ports: 'Front: 1x USB 3.2 Gen 2x2 Type-C, 2x USB 3.2 Gen 1, Audio Jack | Rear: 1x USB 3.2 Gen 2x2 Type-C, 11x USB-A, 2.5G LAN, HDMI 2.1, 3x DP 1.4a',
      os: 'Windows 11 Pro 64-bit (Pre-activated & Driver Calibrated)',
      warranty: '3-Year Comprehensive A2Z Direct Hardware Warranty + On-Site Diagnostics'
    },
    description: 'Engineered for demanding 4K/8K Unreal Engine workflows, Blender 3D rendering, machine learning inference, and uncompromised 4K ray-traced gaming. The A2Z Titan-Forge combines hand-tuned component selection with custom cable routing and multi-stage thermal stress testing.',
    isDemo: true
  },
  {
    id: 'asus-rog-strix-gt35',
    type: 'new',
    brand: 'ASUS',
    model: 'ASUS ROG Strix GT35 Gaming Desktop',
    tagline: 'Esports Tournament Powerhouse with Keystone II & Dual Hot-Swap Drive Bays',
    category: 'Gaming PC',
    processor: 'AMD Ryzen 7 7800X3D (8-Core 3D V-Cache)',
    ram: '32GB DDR5 5600MHz',
    storage: '1TB M.2 PCIe 4.0 SSD',
    graphics: 'NVIDIA GeForce RTX 4070 Ti Super 16GB',
    price: 194990,
    priceDisplay: '₹1,94,990',
    availability: 'In Stock',
    badge: 'Esports 240+ FPS',
    image: 'assets/products/desktop-gaming.jpg',
    gallery: [
      'assets/products/desktop-gaming.jpg',
      'assets/products/desktop-tower.jpg',
      'assets/products/desktop-custom.jpg'
    ],
    shortSpecs: 'Ryzen 7 7800X3D • 32GB DDR5 • 1TB NVMe • RTX 4070 Ti Super 16GB • 240mm Liquid Cooler',
    fullSpecs: {
      processor: 'AMD Ryzen 7 7800X3D (8 Cores, 16 Threads, 104MB Total Cache with 3D V-Cache, up to 5.0 GHz)',
      ram: '32GB (2x16GB) DDR5 5600MHz Dual-Channel (Expandable to 128GB)',
      storage: '1TB M.2 NVMe PCIe 4.0 SSD + 2x Hot-Swap 2.5" SSD Drive Bays on Front Panel',
      graphics: 'NVIDIA GeForce RTX 4070 Ti Super 16GB GDDR6X',
      motherboard: 'ASUS ROG Strix B650 Gaming Motherboard with Aura Sync RGB',
      powerSupply: '850W 80 PLUS Gold Certified High-Efficiency Modular Power Supply',
      coolingChassis: 'ROG Strix Windshear Airflow Chassis with Integrated Carrying Handle & 240mm Liquid AIO',
      ports: 'Front: 2x USB 3.2 Gen 1 Type-A, 2x USB 3.2 Gen 1 Type-C, Mic/Audio | Rear: 6x USB 3.2, 2.5G LAN, Wi-Fi 6E, HDMI 2.1, 3x DP 1.4',
      os: 'Windows 11 Home 64-bit',
      warranty: '2-Year ASUS On-Site Manufacturer Warranty'
    },
    description: 'The ASUS ROG Strix GT35 is built for high-refresh competitive esports titles and ray-traced AAA gaming. With AMD 3D V-Cache architecture, it maintains record-breaking minimum 1% frame times in competitive multiplayer games while keeping acoustics whisper-quiet.',
    isDemo: true
  },
  {
    id: 'dell-precision-3660-tower',
    type: 'new',
    brand: 'Dell',
    model: 'Dell Precision 3660 Tower Workstation',
    tagline: 'ISV-Certified Enterprise Tower for CAD, Engineering & SolidWorks',
    category: 'Workstation Tower',
    processor: 'Intel Core i7-14700 (20-Core, up to 5.4GHz)',
    ram: '32GB DDR5 ECC / Non-ECC 5600MHz',
    storage: '1TB M.2 PCIe Gen4 SSD + 2TB SATA HDD',
    graphics: 'NVIDIA RTX A2000 12GB ECC Professional GPU',
    price: 154990,
    priceDisplay: '₹1,54,990',
    availability: 'In Stock',
    badge: 'ISV Certified',
    image: 'assets/products/desktop-workstation.jpg',
    gallery: [
      'assets/products/desktop-workstation.jpg',
      'assets/products/desktop-dell.jpg',
      'assets/products/desktop-tower.jpg'
    ],
    shortSpecs: 'Core i7-14700 • 32GB DDR5 • 1TB SSD + 2TB HDD • NVIDIA RTX A2000 12GB ECC • 500W Platinum',
    fullSpecs: {
      processor: 'Intel Core i7-14700 (20 Cores: 8 Performance + 12 Efficient, 28 Threads, up to 5.4 GHz Turbo)',
      ram: '32GB (2x16GB) DDR5 5600MHz ECC / Non-ECC (4 DIMM Slots, Expandable to 128GB)',
      storage: '1TB PCIe NVMe Gen4 Class 40 Solid State Drive + 2TB 7200 RPM Enterprise HDD',
      graphics: 'NVIDIA RTX A2000 12GB GDDR6 Professional Workstation GPU with Error Correcting Code (ECC)',
      motherboard: 'Dell Proprietary Intel W680 Workstation Chipset with vPro Remote Management',
      powerSupply: '500W EPA Internal PSU, 80 PLUS Platinum Certified (92% Efficiency)',
      coolingChassis: 'Precision Tower Chassis with Advanced Front Airflow Ducting & Quiet Fan Curve',
      ports: 'Front: 1x USB 3.2 Gen 2 Type-C, 2x USB 3.2 Gen 1, SD Card Reader, Audio | Rear: 4x USB 3.2, 2x USB 2.0, Gigabit LAN, 4x Mini-DP 1.4',
      os: 'Windows 11 Pro 64-bit for Workstations',
      warranty: '3-Year Dell ProSupport with Next Business Day Onsite Service'
    },
    description: 'Designed specifically for civil engineers, mechanical designers, architects, and data analysts. The Dell Precision 3660 offers ISV certifications for AutoCAD, Revit, SolidWorks, and Adobe Creative Cloud, backed by Dell reliable ProSupport guarantee.',
    isDemo: true
  },
  {
    id: 'hp-envy-desktop-te02',
    type: 'new',
    brand: 'HP',
    model: 'HP ENVY Desktop TE02 High-Performance Tower',
    tagline: 'Sleek Aluminum Creator Tower with Tool-Less Expansion',
    category: 'Creator & Office PC',
    processor: 'Intel Core i7-14700F (20-Core, up to 5.4GHz)',
    ram: '32GB DDR5 5200MHz',
    storage: '1TB PCIe Gen4 NVMe SSD',
    graphics: 'NVIDIA GeForce RTX 4060 Ti 8GB GDDR6',
    price: 129990,
    priceDisplay: '₹1,29,990',
    availability: 'In Stock',
    badge: 'Creator Studio',
    image: 'assets/products/desktop-tower.jpg',
    gallery: [
      'assets/products/desktop-tower.jpg',
      'assets/products/desktop-office.jpg',
      'assets/products/desktop-workstation.jpg'
    ],
    shortSpecs: 'Core i7-14700F • 32GB DDR5 • 1TB NVMe • RTX 4060 Ti 8GB • Tool-Less Brushed Chassis',
    fullSpecs: {
      processor: 'Intel Core i7-14700F (20 Cores, 28 Threads, 33MB Cache, up to 5.4 GHz)',
      ram: '32GB (2x16GB) DDR5 5200MHz (Expandable to 64GB)',
      storage: '1TB Western Digital Black SN770 PCIe Gen4 M.2 NVMe SSD',
      graphics: 'NVIDIA GeForce RTX 4060 Ti 8GB GDDR6 Dedicated Graphics',
      motherboard: 'HP Intel B760 Micro-ATX Motherboard with Wi-Fi 6E & Bluetooth 5.3',
      powerSupply: '600W 80 PLUS Gold Certified Internal Power Supply',
      coolingChassis: 'HP Envy Brushed Aluminum Mid-Tower with Tool-Less Side Panel & 120mm Exhaust',
      ports: 'Top/Front: 1x Thunderbolt 4 / USB-C, 3x USB-A 5Gbps, Combo Audio | Rear: 4x USB 2.0, 1x RJ-45 LAN, 1x HDMI 2.1, 3x DisplayPort 1.4a',
      os: 'Windows 11 Home 64-bit + Microsoft Office 2024 Home & Student',
      warranty: '1-Year HP On-Site Hardware Warranty'
    },
    description: 'Combining minimalist brushed aluminum aesthetics with workstation performance. The HP Envy TE02 makes editing multi-cam 4K timeline footage in Premiere Pro and running modern creative applications effortless and quiet.',
    isDemo: true
  },
  {
    id: 'lenovo-legion-tower-5i',
    type: 'new',
    brand: 'Lenovo',
    model: 'Lenovo Legion Tower 5i Gen 8 Gaming PC',
    tagline: 'Vented Mesh Front with 5x ARGB Fans & Storm Grey Tempered Glass',
    category: 'Gaming PC',
    processor: 'Intel Core i5-14400F (10-Core, up to 4.7GHz)',
    ram: '16GB DDR5 5600MHz (Upgradeable)',
    storage: '1TB M.2 PCIe Gen4 NVMe SSD',
    graphics: 'NVIDIA GeForce RTX 4060 8GB GDDR6',
    price: 98990,
    priceDisplay: '₹98,990',
    availability: 'In Stock',
    badge: 'Best Value 1080p/1440p',
    image: 'assets/products/desktop-gaming.jpg',
    gallery: [
      'assets/products/desktop-gaming.jpg',
      'assets/products/desktop-tower.jpg',
      'assets/products/desktop-custom.jpg'
    ],
    shortSpecs: 'Core i5-14400F • 16GB DDR5 • 1TB NVMe • RTX 4060 8GB • 5x ARGB Fans • 500W PSU',
    fullSpecs: {
      processor: 'Intel Core i5-14400F (10 Cores: 6P + 4E, 16 Threads, up to 4.7 GHz Turbo Boost)',
      ram: '16GB (1x16GB) DDR5 5600MHz (Dual Channel Ready, 4 Slots, Expandable to 64GB)',
      storage: '1TB M.2 2280 PCIe 4.0x4 NVMe SSD',
      graphics: 'NVIDIA GeForce RTX 4060 8GB GDDR6 with Ray Tracing & DLSS 3',
      motherboard: 'Lenovo Intel B760 MATX Gaming Motherboard',
      powerSupply: '500W 80 PLUS Bronze Internal Power Supply',
      coolingChassis: '26L Legion Tower with Full Mesh Front Bezel, Tempered Glass Side & 5 ARGB System Fans',
      ports: 'Top: 2x USB 3.2 Gen 1, Headphone Jack, Mic | Rear: 2x USB 3.2 Gen 1, 2x USB 2.0, 1x USB-C 3.2 Gen 2, 2.5G LAN, 1x HDMI 2.1, 3x DP 1.4',
      os: 'Windows 11 Home 64-bit',
      warranty: '3-Year Lenovo Legion Ultimate Support with Next Business Day Onsite'
    },
    description: 'The Lenovo Legion Tower 5i Gen 8 delivers remarkable 1080p and 1440p gaming performance in a chassis built for maximum thermal airflow. Its high-efficiency fan curves keep operational noise low during intense multiplayer battles.',
    isDemo: true
  },
  {
    id: 'acer-predator-orion-3000',
    type: 'new',
    brand: 'Acer',
    model: 'Acer Predator Orion 3000 Compact Gaming Tower',
    tagline: 'FrostBlade 2.0 ARGB Cooling & DTS:X Ultra Spatial Audio',
    category: 'Gaming PC',
    processor: 'Intel Core i7-13700F (16-Core, up to 5.2GHz)',
    ram: '16GB DDR5 4800MHz',
    storage: '1TB M.2 PCIe 4.0 SSD',
    graphics: 'NVIDIA GeForce RTX 4060 Ti 8GB',
    price: 114990,
    priceDisplay: '₹1,14,990',
    availability: 'Limited Stock',
    badge: 'Compact Gaming',
    image: 'assets/products/desktop-tower.jpg',
    gallery: [
      'assets/products/desktop-tower.jpg',
      'assets/products/desktop-gaming.jpg',
      'assets/products/desktop-compact.jpg'
    ],
    shortSpecs: 'Core i7-13700F • 16GB DDR5 • 1TB SSD • RTX 4060 Ti 8GB • FrostBlade 2.0 RGB Fans',
    fullSpecs: {
      processor: 'Intel Core i7-13700F (16 Cores: 8P + 8E, 24 Threads, 30MB Cache, up to 5.2 GHz)',
      ram: '16GB DDR5 4800MHz (2x8GB Dual Channel, 4 Slots, up to 64GB)',
      storage: '1TB M.2 PCIe NVMe Solid State Drive',
      graphics: 'NVIDIA GeForce RTX 4060 Ti 8GB GDDR6',
      motherboard: 'Acer Predator Intel B760 Gaming Motherboard',
      powerSupply: '500W 80 PLUS Gold Certified Power Supply',
      coolingChassis: 'Compact 18L Chassis with EMI-Compliant Tempered Glass & 2x FrostBlade 2.0 ARGB Fans',
      ports: 'Front: 1x USB 3.2 Gen 2 Type-C, 1x USB 3.2 Gen 2 Type-A, Audio Jacks | Rear: 4x USB 2.0, 2x USB 3.2 Gen 1, Gigabit LAN, 1x HDMI 2.1, 3x DP 1.4',
      os: 'Windows 11 Home 64-bit',
      warranty: '2-Year Acer On-Site Warranty'
    },
    description: 'Compact yet formidable, the Acer Predator Orion 3000 packs serious processing muscle into a space-efficient 18-liter tower. Custom FrostBlade 2.0 fans generate strong static pressure while keeping internal noise hushed.',
    isDemo: true
  },
  {
    id: 'hp-pro-tower-280-g9',
    type: 'new',
    brand: 'HP',
    model: 'HP Pro Tower 280 G9 Commercial Business PC',
    tagline: 'Reliable Everyday Office Workhorse with Expandable PCI Slots',
    category: 'Office & Business PC',
    processor: 'Intel Core i5-13400 (10-Core, up to 4.6GHz)',
    ram: '16GB DDR4 3200MHz',
    storage: '512GB PCIe NVMe SSD',
    graphics: 'Intel UHD Graphics 730 (Integrated)',
    price: 46990,
    priceDisplay: '₹46,990',
    availability: 'In Stock',
    badge: 'Corporate Office',
    image: 'assets/products/desktop-office.jpg',
    gallery: [
      'assets/products/desktop-office.jpg',
      'assets/products/desktop-compact.jpg',
      'assets/products/desktop-dell.jpg'
    ],
    shortSpecs: 'Core i5-13400 • 16GB DDR4 • 512GB NVMe SSD • Intel UHD 730 • 180W EPA Power Supply',
    fullSpecs: {
      processor: 'Intel Core i5-13400 (10 Cores: 6P + 4E, 16 Threads, 20MB Cache, up to 4.6 GHz)',
      ram: '16GB (1x16GB) DDR4 3200MHz (2 DIMM Slots, Expandable to 64GB)',
      storage: '512GB PCIe NVMe M.2 SSD + 1x 3.5" HDD SATA Bay Available',
      graphics: 'Intel UHD Graphics 730 with Dual Display Support (HDMI + VGA)',
      motherboard: 'HP Intel H670 Business Motherboard with TPM 2.0 Hardware Security',
      powerSupply: '180W Internal Power Supply, up to 90% Efficiency, Active PFC',
      coolingChassis: 'Commercial Microtower with Low-Noise System Fan & Security Lock Slot',
      ports: 'Front: 4x SuperSpeed USB Type-A 5Gbps, 1x Combo Audio | Rear: 4x USB 2.0 Type-A, 1x HDMI 1.4b, 1x VGA, 1x RJ-45 LAN, Line-in/out',
      os: 'Windows 11 Pro 64-bit Lifetime Licensed',
      warranty: '3-Year HP Commercial Onsite Warranty'
    },
    description: 'Engineered for smooth multitasking, accounting, banking software, ERP databases, and corporate documentation. Includes hardware-level TPM 2.0 security chip and commercial longevity.',
    isDemo: true
  },
  {
    id: 'a2z-creator-zenith-ryzen9',
    type: 'new',
    brand: 'Custom A2Z',
    model: 'A2Z Creator-Zenith AMD Ryzen 9 7950X',
    tagline: '32-Thread Precision Workstation for DaVinci Resolve & 3D CAD',
    category: 'Custom-Built Workstation',
    processor: 'AMD Ryzen 9 7950X (16-Core, 32-Thread, up to 5.7GHz)',
    ram: '64GB DDR5 5600MHz Dual-Channel',
    storage: '2TB Gen4 M.2 NVMe SSD',
    graphics: 'NVIDIA GeForce RTX 4070 Ti 12GB GDDR6X',
    price: 219990,
    priceDisplay: '₹2,19,990',
    availability: 'In Stock (Custom Assembly)',
    badge: 'Creator Master',
    image: 'assets/products/desktop-custom.jpg',
    gallery: [
      'assets/products/desktop-custom.jpg',
      'assets/products/desktop-workstation.jpg',
      'assets/products/desktop-tower.jpg'
    ],
    shortSpecs: 'Ryzen 9 7950X • 64GB DDR5 • 2TB Gen4 SSD • RTX 4070 Ti 12GB • Noctua NH-D15 Air Cooling',
    fullSpecs: {
      processor: 'AMD Ryzen 9 7950X (16 Cores, 32 Threads, 80MB Total Cache, up to 5.7 GHz Max Boost)',
      ram: '64GB (2x32GB) Kingston Fury Beast DDR5 5600MHz CL36 (Dual Channel)',
      storage: '2TB Kingston KC3000 PCIe 4.0 NVMe M.2 SSD (7000 MB/s Read/Write)',
      graphics: 'ZOTAC Gaming GeForce RTX 4070 Ti Trinity OC 12GB GDDR6X',
      motherboard: 'MSI MAG X670E TOMAHAWK WIFI (PCIe 5.0 x16, 4x M.2, Wi-Fi 6E)',
      powerSupply: 'Seasonic Focus GX-850 850W 80 PLUS Gold Fully Modular Power Supply',
      coolingChassis: 'Fractal Design North Charcoal Black (Real Walnut Wood Front) + Noctua NH-D15 chromax.black Cooler',
      ports: 'Front: 1x USB 3.2 Gen 2x2 Type-C, 2x USB 3.0, Audio | Rear: 1x USB-C 20Gbps, 7x USB-A, 2.5G LAN, Optical S/PDIF, Wi-Fi 6E, HDMI 2.1, 3x DP 1.4',
      os: 'Windows 11 Pro 64-bit Pre-Configured',
      warranty: '3-Year A2Z Custom Hardware Warranty with Direct Tech Support'
    },
    description: 'Designed for video creators who prefer silent air-cooling and refined organic aesthetics. The real walnut wood front of the Fractal North chassis houses an absolute powerhouse capable of multi-stream 8K scrubbing and fast color grading.',
    isDemo: true
  },

  // =========================================================================
  // 2. REFURBISHED DESKTOP COMPUTERS (CERTIFIED BUSINESS DESKTOPS)
  // =========================================================================
  {
    id: 'refurb-dell-optiplex-7080-sff',
    type: 'refurbished',
    brand: 'Dell',
    model: 'Dell OptiPlex 7080 SFF (Small Form Factor)',
    tagline: 'Enterprise Workhorse Refurbished with Fresh NVMe & Dual Display Support',
    category: 'Enterprise SFF Desktop',
    processor: 'Intel Core i7-10700 (8-Core, 16-Thread, up to 4.8GHz)',
    ram: '16GB DDR4 2933MHz (Expandable to 128GB)',
    storage: '512GB Fast M.2 NVMe SSD + 1TB SATA HDD',
    graphics: 'Intel UHD Graphics 630 (Supports Dual 4K Monitors)',
    price: 24990,
    priceDisplay: '₹24,990',
    availability: 'In Stock',
    badge: 'Grade A+ Enterprise',
    conditionGrade: 'Grade A+ Pristine',
    testingStatus: '40-Point Hardware Diagnostic Passed',
    includedAccessories: 'Original Power Cord, USB Keyboard & Mouse Set, DisplayPort to HDMI Cable',
    image: 'assets/products/desktop-dell.jpg',
    gallery: [
      'assets/products/desktop-dell.jpg',
      'assets/products/desktop-compact.jpg',
      'assets/products/desktop-office.jpg'
    ],
    shortSpecs: 'Core i7-10700 • 16GB RAM • 512GB NVMe + 1TB HDD • Dual DP Outputs • Grade A+ • 1-Yr Warranty',
    fullSpecs: {
      processor: 'Intel Core i7-10700 (8 Cores, 16 Threads, 16MB Intel Smart Cache, 2.90 GHz Base, up to 4.80 GHz Turbo)',
      ram: '16GB (2x8GB) DDR4 2933MHz Dual Channel (4 DIMM Slots, Supports up to 128GB)',
      storage: '512GB New Western Digital NVMe M.2 SSD (OS Installed) + 1TB Seagate 7200 RPM Storage HDD',
      graphics: 'Intel UHD Graphics 630 Integrated GPU (Supports Dual 4K 60Hz Displays via DisplayPort)',
      motherboard: 'Dell Q470 Enterprise Chipset Motherboard with TPM 2.0 Security Module',
      powerSupply: 'Dell 200W 80 PLUS Platinum High-Efficiency SFF Internal Power Supply',
      coolingChassis: 'Compact Tool-Less Small Form Factor (SFF) Chassis with Low Acoustic Noise Profile',
      ports: 'Front: 1x USB-C 3.2 Gen 2, 1x USB 3.2 Gen 2, 2x USB 2.0, Headset Jack | Rear: 4x USB 3.2 Gen 1, 2x USB 2.0, 2x DisplayPort 1.4, 1x RJ-45 Gigabit Ethernet',
      os: 'Windows 11 Pro 64-bit Genuine Digital License',
      warranty: '1-Year A2Z Hardware Replacement Warranty & 7-Day Money-Back Inspection Policy'
    },
    description: 'Ex-corporate lease desktop, thoroughly inspected, cleaned, thermal re-pasted, and benchmarked by A2Z technicians. Equipped with a brand-new high-speed NVMe SSD, this OptiPlex 7080 boots in seconds and handles office applications, data analysis, accounting, and multi-monitor setups effortlessly.',
    isDemo: true
  },
  {
    id: 'refurb-hp-elitedesk-800-g6-sff',
    type: 'refurbished',
    brand: 'HP',
    model: 'HP EliteDesk 800 G6 SFF Desktop',
    tagline: 'High-Security Corporate Desktop with 10th Gen Core i5 & Clean Thermal Paste',
    category: 'Enterprise SFF Desktop',
    processor: 'Intel Core i5-10500 (6-Core, 12-Thread, up to 4.5GHz)',
    ram: '16GB DDR4 2666MHz',
    storage: '512GB PCIe M.2 NVMe SSD',
    graphics: 'Intel UHD Graphics 630',
    price: 19990,
    priceDisplay: '₹19,990',
    availability: 'In Stock',
    badge: 'Grade A+ Corporate',
    conditionGrade: 'Grade A+ Refurbished',
    testingStatus: 'A2Z 35-Point Hardware Stress Tested',
    includedAccessories: 'Power Cable, Brand-New Wired Keyboard & Optical Mouse',
    image: 'assets/products/desktop-office.jpg',
    gallery: [
      'assets/products/desktop-office.jpg',
      'assets/products/desktop-compact.jpg',
      'assets/products/desktop-dell.jpg'
    ],
    shortSpecs: 'Core i5-10500 • 16GB RAM • 512GB NVMe SSD • Intel UHD 630 • Grade A+ • 1-Yr Warranty',
    fullSpecs: {
      processor: 'Intel Core i5-10500 (6 Cores, 12 Threads, 12MB Cache, 3.10 GHz Base, up to 4.50 GHz Turbo)',
      ram: '16GB DDR4 2666MHz (Expandable to 64GB across 4 DIMM slots)',
      storage: '512GB High-Speed M.2 NVMe Solid State Drive',
      graphics: 'Intel UHD Graphics 630 with 2x DisplayPort 1.4 Outputs',
      motherboard: 'HP Intel Q470 Commercial Motherboard with HP Sure Start Self-Healing BIOS',
      powerSupply: '260W Active PFC 80 PLUS Platinum Certified Internal Power Unit',
      coolingChassis: 'Heavy-Duty Steel SFF Chassis with Dust Filter and Tool-Less Drive Caddies',
      ports: 'Front: 1x USB-C 10Gbps, 2x USB-A 10Gbps, 2x USB-A 5Gbps, Combo Audio | Rear: 6x USB-A, 2x DisplayPort 1.4, 1x RJ-45 LAN',
      os: 'Windows 11 Pro 64-bit Genuine Digital License',
      warranty: '1-Year A2Z Hardware Replacement Warranty & Lifetime Driver Assistance'
    },
    description: 'Renowned for industrial-grade build quality and whisper-quiet fans. The EliteDesk 800 G6 SFF has passed strict multi-point hardware verification including RAM stress tests, NVMe health assessment, and port validation.',
    isDemo: true
  },
  {
    id: 'refurb-lenovo-thinkcentre-m720q-tiny',
    type: 'refurbished',
    brand: 'Lenovo',
    model: 'Lenovo ThinkCentre M720q Tiny Mini PC',
    tagline: 'Ultra-Compact 1-Liter Desktop for Minimalist Desks & POS Counters',
    category: 'Ultra-Compact Tiny PC',
    processor: 'Intel Core i5-8400T (6-Core, up to 3.3GHz)',
    ram: '16GB DDR4 RAM',
    storage: '512GB M.2 NVMe SSD',
    graphics: 'Intel UHD Graphics 630',
    price: 15990,
    priceDisplay: '₹15,990',
    availability: 'In Stock',
    badge: '1-Liter Pocket PC',
    conditionGrade: 'Grade A Refurbished',
    testingStatus: 'Full Thermal & Power Cycle Benchmark Passed',
    includedAccessories: 'Original Lenovo 65W AC Adapter & Power Cord, VESA Monitor Mount Bracket',
    image: 'assets/products/desktop-compact.jpg',
    gallery: [
      'assets/products/desktop-compact.jpg',
      'assets/products/desktop-dell.jpg',
      'assets/products/desktop-office.jpg'
    ],
    shortSpecs: 'Core i5-8400T • 16GB DDR4 • 512GB NVMe • Ultra-Compact 1L Body • VESA Mountable • Grade A',
    fullSpecs: {
      processor: 'Intel Core i5-8400T (6 Cores, 6 Threads, 9MB Smart Cache, up to 3.30 GHz Turbo Boost)',
      ram: '16GB (2x8GB) DDR4 SO-DIMM (Dual Channel, Expandable to 32GB)',
      storage: '512GB M.2 2280 NVMe SSD + 1x 2.5" SATA SSD/HDD Caddy Available',
      graphics: 'Intel UHD Graphics 630 with 1x HDMI and 1x DisplayPort Dual Output',
      motherboard: 'Lenovo Intel B360 Chipset with Fast Boot & Hardware TPM 2.0',
      powerSupply: 'Original External 65W AC Power Adapter (88% Efficiency)',
      coolingChassis: 'Ultra-Compact 1-Liter Chassis (17.9cm x 18.2cm x 3.45cm, Weight: 1.32 kg)',
      ports: 'Front: 1x USB-C 3.1 Gen 1, 1x USB 3.1 Gen 1 (Always On fast charge), Mic/Headphone | Rear: 2x USB 3.1 Gen 2, 2x USB 3.1 Gen 1, 1x HDMI, 1x DisplayPort, RJ-45 LAN',
      os: 'Windows 11 Pro 64-bit Pre-Installed',
      warranty: '1-Year A2Z Hardware Replacement Warranty'
    },
    description: 'At roughly the size of a paperback book, the Lenovo ThinkCentre M720q Tiny can be mounted directly behind a monitor with the included VESA bracket. Remarkable power efficiency, virtually silent operation, and reliable multi-monitor support.',
    isDemo: true
  },
  {
    id: 'refurb-dell-precision-3640-tower',
    type: 'refurbished',
    brand: 'Dell',
    model: 'Dell Precision 3640 Tower Workstation (Certified)',
    tagline: 'High-Expansion Refurbished Tower for 3D Modeling & Trading Multi-Screens',
    category: 'Refurbished Workstation',
    processor: 'Intel Core i7-10700K (8-Core, up to 5.1GHz Unlocked)',
    ram: '32GB DDR4 3200MHz',
    storage: '1TB M.2 NVMe SSD + 2TB HDD',
    graphics: 'NVIDIA Quadro P2200 5GB (Supports 4x 5K Displays)',
    price: 44990,
    priceDisplay: '₹44,990',
    availability: 'Limited Stock',
    badge: 'Quadro 4-Display',
    conditionGrade: 'Grade A+ Workstation',
    testingStatus: 'Continuous 24-Hour Prime95 & FurMark Stress Passed',
    includedAccessories: 'Heavy-Duty Power Cable, DisplayPort to HDMI Adapters (x2), A2Z Keyboard/Mouse Combo',
    image: 'assets/products/desktop-tower.jpg',
    gallery: [
      'assets/products/desktop-tower.jpg',
      'assets/products/desktop-dell.jpg',
      'assets/products/desktop-workstation.jpg'
    ],
    shortSpecs: 'Core i7-10700K • 32GB RAM • 1TB NVMe + 2TB HDD • Quadro P2200 5GB • 4x DP Outputs • Grade A+',
    fullSpecs: {
      processor: 'Intel Core i7-10700K Unlocked (8 Cores, 16 Threads, 16MB Cache, 3.80 GHz Base, up to 5.10 GHz Turbo)',
      ram: '32GB (2x16GB) DDR4 3200MHz (4 DIMM Slots, Expandable to 128GB)',
      storage: '1TB New PCIe Gen3x4 NVMe SSD + 2TB Seagate Barracuda 7200 RPM Secondary Drive',
      graphics: 'NVIDIA Quadro P2200 5GB GDDR5 Workstation GPU (4x DisplayPort 1.4 Native Outputs)',
      motherboard: 'Dell Intel W480 Workstation Motherboard with ECC & Non-ECC Support',
      powerSupply: 'Dell 550W 80 PLUS Gold Certified Internal Power Supply (PCIe Power Cables Available for GPU Upgrades)',
      coolingChassis: 'Precision Tower Chassis with High-Static Pressure Intake & Exhaust Fans',
      ports: 'Front: 1x USB-C 3.2 Gen 2, 3x USB 3.2 Gen 1, Audio Jack | Rear: 4x USB 3.2 Gen 1, 2x USB 2.0, 4x DisplayPort on Quadro GPU, Gigabit LAN',
      os: 'Windows 11 Pro for Workstations Genuine License',
      warranty: '1-Year Comprehensive A2Z On-Site Hardware Replacement Warranty'
    },
    description: 'An exceptional high-expansion workstation certified for stock trading desks, architecture studios, and video editing. The included NVIDIA Quadro P2200 drives up to four 5K displays simultaneously with flicker-free professional stability.',
    isDemo: true
  },
  {
    id: 'refurb-hp-prodesk-400-g6-microtower',
    type: 'refurbished',
    brand: 'HP',
    model: 'HP ProDesk 400 G6 Microtower PC',
    tagline: 'Expandable Business Desktop with Dedicated PCIe Slots & Cleaned Thermals',
    category: 'Refurbished Business PC',
    processor: 'Intel Core i3-10100 (4-Core, 8-Thread, up to 4.3GHz)',
    ram: '16GB DDR4 2666MHz',
    storage: '256GB M.2 NVMe SSD + 500GB HDD',
    graphics: 'Intel UHD Graphics 630',
    price: 14490,
    priceDisplay: '₹14,490',
    availability: 'In Stock',
    badge: 'Budget Office Pick',
    conditionGrade: 'Grade A Refurbished',
    testingStatus: 'Full Hardware Check & Cleaned Interior',
    includedAccessories: 'Original Power Cord, USB Keyboard & Optical Mouse',
    image: 'assets/products/desktop-office.jpg',
    gallery: [
      'assets/products/desktop-office.jpg',
      'assets/products/desktop-compact.jpg',
      'assets/products/desktop-dell.jpg'
    ],
    shortSpecs: 'Core i3-10100 • 16GB RAM • 256GB NVMe + 500GB HDD • Microtower Expansion • Grade A',
    fullSpecs: {
      processor: 'Intel Core i3-10100 (4 Cores, 8 Threads, 6MB Cache, 3.60 GHz Base, up to 4.30 GHz Turbo Boost)',
      ram: '16GB (1x16GB) DDR4 2666MHz (2 DIMM Slots, Expandable to 64GB)',
      storage: '256GB M.2 PCIe NVMe SSD (New OS Drive) + 500GB 7200 RPM Secondary HDD',
      graphics: 'Intel UHD Graphics 630 (1x HDMI, 1x DisplayPort)',
      motherboard: 'HP Intel H470 Micro-ATX Business Motherboard with TPM 2.0',
      powerSupply: '180W Active PFC High Efficiency Power Supply',
      coolingChassis: 'Sturdy Microtower with Free Full-Height PCIe x16 Slot for Future Graphic Card Upgrades',
      ports: 'Front: 2x USB 3.2 Gen 1, Combo Audio | Rear: 4x USB 2.0, 2x USB 3.2 Gen 1, 1x HDMI, 1x DisplayPort, RJ-45 LAN',
      os: 'Windows 11 Pro 64-bit Genuine Digital License',
      warranty: '1-Year A2Z Hardware Replacement Warranty'
    },
    description: 'An affordable desktop solution for billing counters, administrative offices, students, and light graphic design. Its microtower form factor allows easy expansion with additional hard drives or low-profile dedicated graphics cards.',
    isDemo: true
  },
  {
    id: 'refurb-acer-veriton-m4660g-tower',
    type: 'refurbished',
    brand: 'Acer',
    model: 'Acer Veriton M4660G Commercial Tower',
    tagline: 'Robust Commercial Grade Desktop with Dual Monitor VGA + HDMI Outputs',
    category: 'Commercial Tower',
    processor: 'Intel Core i5-9500 (6-Core, up to 4.4GHz)',
    ram: '16GB DDR4 2666MHz',
    storage: '512GB M.2 NVMe SSD',
    graphics: 'Intel UHD Graphics 630',
    price: 16990,
    priceDisplay: '₹16,990',
    availability: 'In Stock',
    badge: 'Commercial Grade A',
    conditionGrade: 'Grade A+ Inspected',
    testingStatus: 'Burn-in Memory & Motherboard Diagnostic Cleared',
    includedAccessories: 'Power Cord, Wired Keyboard & Mouse',
    image: 'assets/products/desktop-compact.jpg',
    gallery: [
      'assets/products/desktop-compact.jpg',
      'assets/products/desktop-office.jpg',
      'assets/products/desktop-dell.jpg'
    ],
    shortSpecs: 'Core i5-9500 • 16GB DDR4 • 512GB NVMe SSD • Dual Display Output • Grade A+ • 1-Yr Warranty',
    fullSpecs: {
      processor: 'Intel Core i5-9500 (6 Cores, 6 Threads, 9MB Cache, 3.00 GHz Base, up to 4.40 GHz Turbo)',
      ram: '16GB DDR4 2666MHz (Dual Channel, 4 Slots, Expandable to 64GB)',
      storage: '512GB M.2 PCIe NVMe Solid State Drive',
      graphics: 'Intel UHD Graphics 630 with 1x HDMI, 1x DisplayPort, 1x VGA',
      motherboard: 'Acer Intel B360 Commercial Motherboard with Hardware TPM 2.0',
      powerSupply: '300W 80 PLUS Bronze Internal Power Supply',
      coolingChassis: 'Mid-Tower Chassis with Tool-Less Drive Bays & High Air Intake Fan',
      ports: 'Front: 1x USB-C 3.1 Gen 2, 3x USB 3.1 Gen 1, Audio Jacks | Rear: 4x USB 2.0, 2x USB 3.1, 1x HDMI, 1x DisplayPort, 1x VGA, Gigabit LAN',
      os: 'Windows 11 Pro 64-bit Genuine Digital License',
      warranty: '1-Year A2Z Hardware Replacement Warranty'
    },
    description: 'The Acer Veriton M4660G provides exceptional legacy and modern connectivity with triple display outputs (HDMI, DisplayPort, VGA). Perfect for corporate back-offices, legal offices, and educational institutions.',
    isDemo: true
  }
];

// Helper to look up a desktop PC by its ID
function getDesktopById(id) {
  return DESKTOP_DATA.find(item => item.id === id) || null;
}
