/**
 * A2Z COMPUTERS — Monitors Catalog Data Store
 * Structured demo inventory for Creator, Gaming, Curved, and Office Displays.
 * Shared across monitors.html and monitor-details.html.
 */

const MONITOR_DATA = [
  {
    id: 'asus-proart-pa279crv',
    brand: 'ASUS',
    model: 'ProArt Display PA279CRV 27" 4K',
    tagline: 'Factory-Calibrated Color Precision for Visual Creators',
    category: 'Creator Display',
    screenSize: '27"',
    resolution: '4K UHD (3840 x 2160)',
    refreshRate: '60Hz',
    panelType: 'IPS',
    price: 49990,
    priceDisplay: '₹49,990',
    availability: 'In Stock',
    badge: 'Color Accurate',
    image: 'assets/products/monitor.jpg',
    gallery: [
      'assets/products/monitor.jpg',
      'assets/products/monitor-dell.jpg',
      'assets/products/monitor-office.jpg'
    ],
    shortSpecs: '27" 4K UHD • IPS • 99% DCI-P3 • 96W USB-C PD • Calman Verified',
    fullSpecs: {
      screenSize: '27.0 Inches (68.47 cm Diagonal)',
      resolution: '3840 x 2160 (4K UHD 16:9 Aspect Ratio)',
      panelType: 'IPS Anti-Glare with 3H Hard Coating',
      refreshRate: '60Hz',
      responseTime: '5ms (GTG)',
      brightness: '400 nits peak (VESA DisplayHDR 400)',
      colorGamut: '99% DCI-P3, 99% Adobe RGB, 100% sRGB, Factory Calibrated ΔE < 2',
      ports: '1x USB-C (96W Power Delivery, DP Alt Mode), 2x DisplayPort 1.4, 2x HDMI 2.0, USB 3.2 Gen 1 Hub, 3.5mm Earphone Jack',
      adaptiveSync: 'Adaptive-Sync (40Hz - 60Hz)',
      standErgo: 'Full Ergonomic: Tilt (-5°~+23°), Swivel (±30°), Pivot (90° bi-directional), Height (0~130mm)',
      warranty: '3-Year ASUS ProArt On-Site Replacement Warranty'
    },
    description: 'Engineered specifically for videographers, colorists, and digital artists, the ASUS ProArt PA279CRV delivers uncompromised 4K resolution with 99% DCI-P3 and Adobe RGB gamut coverage. Its full-function USB-C port provides superfast data transfer, DisplayPort signal, and 96W power delivery through a single tidy cable.',
    isDemo: true
  },
  {
    id: 'dell-ultrasharp-u2723qe',
    brand: 'Dell',
    model: 'UltraSharp U2723QE 27" 4K USB-C Hub',
    tagline: 'IPS Black Technology with 2000:1 Contrast & Dual-PC KVM',
    category: 'Business & Office',
    screenSize: '27"',
    resolution: '4K UHD (3840 x 2160)',
    refreshRate: '60Hz',
    panelType: 'IPS Black',
    price: 58990,
    priceDisplay: '₹58,990',
    availability: 'In Stock',
    badge: 'IPS Black Hub',
    image: 'assets/products/monitor-dell.jpg',
    gallery: [
      'assets/products/monitor-dell.jpg',
      'assets/products/monitor.jpg',
      'assets/products/monitor-office.jpg'
    ],
    shortSpecs: '27" 4K UHD • IPS Black 2000:1 • 90W USB-C Hub • RJ-45 LAN • KVM',
    fullSpecs: {
      screenSize: '27.0 Inches Active Matrix TFT',
      resolution: '3840 x 2160 at 60Hz (163 PPI Pixel Density)',
      panelType: 'IPS Black Technology (2000:1 Static Contrast Ratio)',
      refreshRate: '60Hz',
      responseTime: '5ms (Fast Mode GTG)',
      brightness: '400 nits (VESA DisplayHDR 400)',
      colorGamut: '100% sRGB, 100% Rec.709, 98% DCI-P3, Delta E < 2',
      ports: '1x USB-C (90W PD), 1x USB-C upstream (data only), 1x DisplayPort 1.4 out (Daisy Chain), 1x DP 1.4 in, 1x HDMI 2.0, 1x RJ-45 Gigabit Ethernet, 5x USB-A 10Gbps',
      adaptiveSync: 'Standard 60Hz VESA Compliant',
      standErgo: 'Height adjustable (150mm), Tilt (-5°/+21°), Swivel (-45°/+45°), Pivot (-90°/+90°)',
      warranty: '3-Year Dell Advanced Exchange Service & Premium Panel Guarantee'
    },
    description: 'The Dell UltraSharp U2723QE is the quintessential productivity command center. Featuring groundbreaking IPS Black technology that achieves twice the contrast of conventional IPS panels, deeper blacks, and an integrated KVM switch allowing seamless control of two connected computers with a single keyboard and mouse.',
    isDemo: true
  },
  {
    id: 'samsung-odyssey-g9',
    brand: 'Samsung',
    model: 'Odyssey OLED G9 49" Curved (G95SC)',
    tagline: 'Dual QHD 1800R Curved OLED Gaming Beast with 0.03ms Response',
    category: 'Curved Ultrawide',
    screenSize: '49"',
    resolution: 'Dual QHD (5120 x 1440)',
    refreshRate: '240Hz',
    panelType: 'QD-OLED',
    price: 139990,
    priceDisplay: '₹1,39,990',
    availability: 'Limited Stock',
    badge: '49" 240Hz OLED',
    image: 'assets/products/monitor-samsung.jpg',
    gallery: [
      'assets/products/monitor-samsung.jpg',
      'assets/products/monitor-curved.jpg',
      'assets/products/monitor-gaming.jpg'
    ],
    shortSpecs: '49" Dual QHD (32:9) • 1800R Curved OLED • 240Hz • 0.03ms • Neo Quantum Processor',
    fullSpecs: {
      screenSize: '49.0 Inches Ultra-Wide 32:9 Super Curved (Equivalent to two 27" QHD side-by-side)',
      resolution: '5120 x 1440 (Dual Quad HD)',
      panelType: 'Quantum Dot OLED (Infinite Contrast Ratio 1,000,000:1)',
      refreshRate: '240Hz Blazing Refresh Rate',
      responseTime: '0.03ms (Gray-to-Gray)',
      brightness: '250 nits typical (DisplayHDR True Black 400)',
      colorGamut: '99% DCI-P3 (CIE1976)',
      ports: '1x DisplayPort 1.4, 1x HDMI 2.1, 1x Micro HDMI 2.1, USB Hub (3x USB 3.0), Built-in 5W Stereo Speakers',
      adaptiveSync: 'AMD FreeSync Premium Pro & G-Sync Compatible',
      standErgo: 'Height Adjustable Stand (120mm) & Tilt (-2° ~ +15°), CoreSync & Core Lighting+ rear illumination',
      warranty: '3-Year Samsung Comprehensive OLED Warranty'
    },
    description: 'Immerse yourself into simulation rigs, open-world adventures, and sprawling timeline editors with the Samsung Odyssey OLED G9. Powered by the Neo Quantum Processor Pro, each frame on the massive 49-inch 1800R curved display is analyzed and enhanced for maximum clarity, rich contrast, and zero motion blur.',
    isDemo: true
  },
  {
    id: 'lg-ultragear-27gr95qe',
    brand: 'LG',
    model: 'UltraGear OLED 27GR95QE 27" 240Hz',
    tagline: 'Pure OLED Tournament Esports Display with 0.03ms Response',
    category: 'Gaming Monitor',
    screenSize: '27"',
    resolution: 'QHD (2560 x 1440)',
    refreshRate: '240Hz',
    panelType: 'OLED',
    price: 69990,
    priceDisplay: '₹69,990',
    availability: 'In Stock',
    badge: '240Hz OLED',
    image: 'assets/products/monitor-lg.jpg',
    gallery: [
      'assets/products/monitor-lg.jpg',
      'assets/products/monitor-gaming.jpg',
      'assets/products/monitor-curved.jpg'
    ],
    shortSpecs: '27" QHD (2560x1440) • 240Hz • 0.03ms • Anti-Glare Low Reflection OLED • G-Sync',
    fullSpecs: {
      screenSize: '26.5 Inches WQHD Gaming Display',
      resolution: '2560 x 1440 (16:9 QHD)',
      panelType: 'LG OLED with Micro Lens Array & AGLR Anti-Glare Coating',
      refreshRate: '240Hz',
      responseTime: '0.03ms (GTG)',
      brightness: '200 nits typical (HDR10 support)',
      colorGamut: 'DCI-P3 98.5% (CIE1976)',
      ports: '2x HDMI 2.1, 1x DisplayPort 1.4 (DSC), 2x USB 3.0 downstream, 1x USB upstream, 4-pole DTS Headphone:X jack, SPDIF Optical Out',
      adaptiveSync: 'NVIDIA G-Sync Compatible & AMD FreeSync Premium',
      standErgo: 'Tilt, Height, Swivel & Pivot Adjustments with Hexagon RGB Rear Lighting',
      warranty: '2-Year LG Panel Replacement Warranty'
    },
    description: 'Equipped with LG’s elite OLED panel technology, the 27GR95QE is built for competitive esports players demanding near-zero input lag. Experience fluid 240Hz frame transitions, instantaneous 0.03ms response times, and true self-lit pixel blacks that ensure high-speed visual clarity.',
    isDemo: true
  },
  {
    id: 'hp-e27k-g4',
    brand: 'HP',
    model: 'HP E27k G4 27" 4K USB-C Business Monitor',
    tagline: 'Ergonomic 4K Productivity Screen with HP Eye Ease',
    category: 'Business & Office',
    screenSize: '27"',
    resolution: '4K UHD (3840 x 2160)',
    refreshRate: '60Hz',
    panelType: 'IPS',
    price: 38990,
    priceDisplay: '₹38,990',
    availability: 'In Stock',
    badge: 'Office 4K',
    image: 'assets/products/monitor-office.jpg',
    gallery: [
      'assets/products/monitor-office.jpg',
      'assets/products/monitor.jpg',
      'assets/products/monitor-dell.jpg'
    ],
    shortSpecs: '27" 4K UHD • IPS • 65W USB-C Single Cable • 4-Way Ergonomics • Eye Ease',
    fullSpecs: {
      screenSize: '27.0 Inches Anti-Glare Micro-Edge IPS',
      resolution: '3840 x 2160 (4K UHD)',
      panelType: 'IPS 3-Sided Borderless',
      refreshRate: '60Hz',
      responseTime: '5ms (with Overdrive)',
      brightness: '350 nits',
      colorGamut: '99% sRGB Gamut Coverage',
      ports: '1x USB Type-C (65W USB Power Delivery, DP 1.4), 1x HDMI 2.0, 1x DisplayPort 1.2, 4x USB-A 3.2 Gen 1 Hub',
      adaptiveSync: 'VESA Standard',
      standErgo: '4-Way Ergonomics: 150mm Height Adjust, Swivel, Tilt, 90° Pivot',
      warranty: '3-Year HP Commercial Onsite Warranty'
    },
    description: 'The HP E27k G4 is tailored for corporate offices, law firms, and multitasking finance analysts. Connect your notebook with a single 65W USB-C cable for simultaneous display, charging, and peripheral expansion, while HP Eye Ease keeps blue light low without distorting natural colors.',
    isDemo: true
  },
  {
    id: 'lenovo-thinkvision-p27u',
    brand: 'Lenovo',
    model: 'ThinkVision P27u-20 27" 4K Thunderbolt 4',
    tagline: 'Professional Graphics Display with Dual Thunderbolt 4 Hub',
    category: 'Creator Display',
    screenSize: '27"',
    resolution: '4K UHD (3840 x 2160)',
    refreshRate: '60Hz',
    panelType: 'IPS',
    price: 64990,
    priceDisplay: '₹64,990',
    availability: 'Available on Order',
    badge: 'Thunderbolt 4',
    image: 'assets/products/monitor-dell.jpg',
    gallery: [
      'assets/products/monitor-dell.jpg',
      'assets/products/monitor-office.jpg',
      'assets/products/monitor.jpg'
    ],
    shortSpecs: '27" 4K UHD • Dual Thunderbolt 4 (100W PD) • 99.1% DCI-P3 • 99.5% Adobe RGB',
    fullSpecs: {
      screenSize: '27.0 Inches In-Plane Switching Panel',
      resolution: '3840 x 2160 (4K UHD)',
      panelType: 'IPS with 10-Bit Color Depth (1.07 Billion Colors)',
      refreshRate: '60Hz',
      responseTime: '4ms (Extreme Mode)',
      brightness: '400 nits typical (VESA DisplayHDR 400)',
      colorGamut: '99.5% Adobe RGB, 99.1% DCI-P3, 100% sRGB, Factory Pre-Calibrated ΔE < 1',
      ports: '1x Thunderbolt 4 in (100W PD), 1x Thunderbolt 4 out (Daisy Chain), 2x HDMI 2.0, 1x DP 1.2, 1x RJ-45 LAN, 3x USB-A 3.2 Gen 1, Audio Out',
      adaptiveSync: 'Standard VESA',
      standErgo: 'Full Ergonomic Stand with Phone Holder & Cable Channel',
      warranty: '3-Year Lenovo Premier Support'
    },
    description: 'A masterclass in creator hardware, the Lenovo ThinkVision P27u-20 is equipped with dual Thunderbolt 4 ports offering up to 100W power delivery and 40Gbps daisy-chain capability. Featuring exceptional 99.5% Adobe RGB fidelity, it is purpose-built for commercial photography and print production.',
    isDemo: true
  },
  {
    id: 'acer-predator-x34',
    brand: 'Acer',
    model: 'Predator X34 V 34" Curved OLED',
    tagline: 'UWQHD 175Hz 1800R Curved OLED Ultra-Fast Gaming Canvas',
    category: 'Curved Ultrawide',
    screenSize: '34"',
    resolution: 'UWQHD (3440 x 1440)',
    refreshRate: '175Hz',
    panelType: 'OLED',
    price: 89990,
    priceDisplay: '₹89,990',
    availability: 'In Stock',
    badge: 'Curved OLED',
    image: 'assets/products/monitor-curved.jpg',
    gallery: [
      'assets/products/monitor-curved.jpg',
      'assets/products/monitor-gaming.jpg',
      'assets/products/monitor.jpg'
    ],
    shortSpecs: '34" UWQHD (3440x1440) • 1800R Curved OLED • 175Hz • 0.1ms • 65W Type-C Hub',
    fullSpecs: {
      screenSize: '34.0 Inches 21:9 Ultrawide Curved Display',
      resolution: '3440 x 1440 (Ultra-Wide Quad HD)',
      panelType: 'OLED 1800R Curved with True Black 400',
      refreshRate: '175Hz (over DisplayPort/Type-C)',
      responseTime: '0.1ms (GTG)',
      brightness: '250 nits base, up to 1000 nits Peak HDR (3% window)',
      colorGamut: '99% DCI-P3 Professional Gamut',
      ports: '1x USB-C (65W PD), 2x HDMI 2.1, 1x DisplayPort 1.4, 2x USB-A 3.2, Built-in 2x 5W Stereo Speakers',
      adaptiveSync: 'AMD FreeSync Premium Pro',
      standErgo: 'Ergonomic Stand: Height Adjustment (120mm), Swivel (±30°), Tilt (-5°~+20°)',
      warranty: '3-Year Acer Onsite Hardware Warranty'
    },
    description: 'The Acer Predator X34 V combines the panoramic wraparound view of an 1800R curved 34-inch ultrawide with the mind-blowing contrast and instant 0.1ms response times of an OLED panel. Perfect for flight simulators, racing titles, and ultra-wide cinematic media creation.',
    isDemo: true
  },
  {
    id: 'asus-rog-swift-pg27aqdm',
    brand: 'ASUS',
    model: 'ROG Swift OLED PG27AQDM 27" 240Hz',
    tagline: 'Custom Heatsink Cooled OLED Gaming Display with 0.03ms',
    category: 'Gaming Monitor',
    screenSize: '27"',
    resolution: 'QHD (2560 x 1440)',
    refreshRate: '240Hz',
    panelType: 'OLED',
    price: 74990,
    priceDisplay: '₹74,990',
    availability: 'In Stock',
    badge: 'ROG Flagship',
    image: 'assets/products/monitor-gaming.jpg',
    gallery: [
      'assets/products/monitor-gaming.jpg',
      'assets/products/monitor-lg.jpg',
      'assets/products/monitor.jpg'
    ],
    shortSpecs: '27" QHD • 240Hz OLED • 0.03ms • Custom Heatsink Cooling • 1000 Nits Peak HDR',
    fullSpecs: {
      screenSize: '26.5 Inches Non-Glare OLED Gaming Monitor',
      resolution: '2560 x 1440 (QHD 16:9)',
      panelType: 'Anti-Glare Micro-Texture OLED Panel',
      refreshRate: '240Hz',
      responseTime: '0.03ms (GTG)',
      brightness: '1000 nits Peak (3% APL HDR), 450 nits (100% APL)',
      colorGamut: '99% DCI-P3, 135% sRGB, Factory Pre-Calibrated ΔE < 2',
      ports: '1x DisplayPort 1.4 (DSC), 2x HDMI 2.0, 2x USB 3.2 Gen 1 Type-A, 1x Earphone Out, Optical SPDIF Out',
      adaptiveSync: 'G-Sync Compatible & AMD FreeSync Premium',
      standErgo: 'ROG Ergonomic Stand with ROG Desk Mount Kit compatibility, AURA Sync Lighting',
      warranty: '2-Year ASUS Burn-In Warranty Protection'
    },
    description: 'The ROG Swift OLED PG27AQDM features a custom heavy-duty aluminum heatsink and intelligent voltage optimization that reduces operating temperatures by up to 5% compared to other OLED monitors, allowing sustained high peak brightness without aggressive dimming.',
    isDemo: true
  },
  {
    id: 'dell-s2721dgf',
    brand: 'Dell',
    model: 'Dell 27" QHD Fast IPS Gaming (S2721DGF)',
    tagline: 'Crisp 165Hz Fast IPS Panel with VESA DisplayHDR 400',
    category: 'Gaming Monitor',
    screenSize: '27"',
    resolution: 'QHD (2560 x 1440)',
    refreshRate: '165Hz',
    panelType: 'Fast IPS',
    price: 31990,
    priceDisplay: '₹31,990',
    availability: 'In Stock',
    badge: 'Best Value Gaming',
    image: 'assets/products/monitor-dell.jpg',
    gallery: [
      'assets/products/monitor-dell.jpg',
      'assets/products/monitor-gaming.jpg',
      'assets/products/monitor-office.jpg'
    ],
    shortSpecs: '27" QHD • 165Hz (DP) / 144Hz (HDMI) • 1ms Fast IPS • 98% DCI-P3 • G-Sync',
    fullSpecs: {
      screenSize: '27.0 Inches Anti-Glare 3-Sided Ultrathin Bezel',
      resolution: '2560 x 1440 at 165Hz',
      panelType: 'Fast IPS Nano Color Technology',
      refreshRate: '165Hz (DisplayPort) / 144Hz (HDMI)',
      responseTime: '1ms (Gray-to-Gray Extreme)',
      brightness: '400 nits (VESA DisplayHDR 400)',
      colorGamut: '98% DCI-P3 Wide Color Gamut',
      ports: '2x HDMI 2.0, 1x DisplayPort 1.4, 4x USB 3.0 downstream, 1x USB 3.0 upstream, Headphone & Audio Line-out',
      adaptiveSync: 'NVIDIA G-Sync Compatible & AMD FreeSync Premium Pro',
      standErgo: 'Height (130mm), Tilt (-5°/+21°), Swivel (-45°/+45°), Pivot (-90°/+90°)',
      warranty: '3-Year Dell Advanced Exchange Service'
    },
    description: 'A benchmark in high-speed 1440p gaming, the Dell S2721DGF delivers vibrant Nano IPS colors with a blisteringly responsive 1ms panel. Dual HDMI ports and a DisplayPort 1.4 connection make it ideal for switching between a high-end gaming PC and current-gen consoles.',
    isDemo: true
  },
  {
    id: 'samsung-viewfinity-s8',
    brand: 'Samsung',
    model: 'ViewFinity S8 32" 4K UHD Matte Display',
    tagline: 'World First UL-Certified Glare-Free Professional 4K Display',
    category: 'Creator Display',
    screenSize: '32"',
    resolution: '4K UHD (3840 x 2160)',
    refreshRate: '60Hz',
    panelType: 'IPS',
    price: 46990,
    priceDisplay: '₹46,990',
    availability: 'In Stock',
    badge: 'Glare-Free 4K',
    image: 'assets/products/monitor-samsung.jpg',
    gallery: [
      'assets/products/monitor-samsung.jpg',
      'assets/products/monitor-office.jpg',
      'assets/products/monitor.jpg'
    ],
    shortSpecs: '32" 4K UHD • Matte Glare-Free IPS • 90W USB-C • 98% DCI-P3 • HDR 600',
    fullSpecs: {
      screenSize: '32.0 Inches 16:9 Big Canvas',
      resolution: '3840 x 2160 (4K UHD)',
      panelType: 'Matte Finish IPS (Zero Reflection UL-Certified)',
      refreshRate: '60Hz',
      responseTime: '5ms (GTG)',
      brightness: '400 nits typical, 600 nits Peak (VESA DisplayHDR 600)',
      colorGamut: '98% DCI-P3, 99% sRGB Pantone Validated',
      ports: '1x USB Type-C (90W Fast Charging), 1x DisplayPort 1.4, 1x HDMI 2.0, 1x Ethernet LAN, 3x USB 3.0 downstream, 3.5mm Headphone Jack',
      adaptiveSync: 'Standard VESA',
      standErgo: 'HAS Height Adjustable Stand, Tilt, Swivel, Pivot',
      warranty: '3-Year Samsung Onsite Warranty'
    },
    description: 'The Samsung ViewFinity S8 features a breakthrough UL-certified Matte Display that completely disperses ambient light reflections, even under harsh studio lights or direct window exposure. Connect, charge, and transmit 4K video using a single 90W USB-C cable.',
    isDemo: true
  },
  {
    id: 'lg-ultrawide-34wp65c',
    brand: 'LG',
    model: 'LG UltraWide 34WP65C 34" Curved 160Hz',
    tagline: 'Panoramic 21:9 Curved Display for Maximum Workspace & Gaming',
    category: 'Curved Ultrawide',
    screenSize: '34"',
    resolution: 'WQHD (3440 x 1440)',
    refreshRate: '160Hz',
    panelType: 'VA',
    price: 36990,
    priceDisplay: '₹36,990',
    availability: 'In Stock',
    badge: '34" Curved 160Hz',
    image: 'assets/products/monitor-curved.jpg',
    gallery: [
      'assets/products/monitor-curved.jpg',
      'assets/products/monitor-lg.jpg',
      'assets/products/monitor.jpg'
    ],
    shortSpecs: '34" WQHD (21:9) • 1800R Curved • 160Hz • 1ms MBR • MaxxAudio 7W Speakers',
    fullSpecs: {
      screenSize: '34.0 Inches Curved 1800R UltraWide 21:9',
      resolution: '3440 x 1440 (Ultra-Wide QHD)',
      panelType: 'Curved VA Panel with 3000:1 High Native Contrast',
      refreshRate: '160Hz (DisplayPort) / 85Hz (HDMI)',
      responseTime: '5ms (GTG), 1ms MBR (Motion Blur Reduction)',
      brightness: '300 nits (HDR10 support)',
      colorGamut: 'sRGB 99% (CIE1931)',
      ports: '1x DisplayPort 1.4, 2x HDMI 2.0, Headphone Out, Stereo Speakers with Waves MaxxAudio (7W x 2)',
      adaptiveSync: 'AMD FreeSync Premium',
      standErgo: 'One-Click Stand with Tilt and Height Adjustability (110mm)',
      warranty: '3-Year LG Onsite Warranty'
    },
    description: 'Expand your productivity horizons with 33% more desktop workspace than standard 16:9 displays. The LG 34WP65C features an immersive 1800R curve, dual built-in 7W MaxxAudio speakers with deep bass, and high 160Hz refresh rate for smooth gaming.',
    isDemo: true
  },
  {
    id: 'hp-omen-27k',
    brand: 'HP',
    model: 'OMEN 27k 27" 4K 144Hz Gaming Monitor',
    tagline: 'High-Speed 4K UHD Gaming with Integrated KVM Switch',
    category: 'Gaming Monitor',
    screenSize: '27"',
    resolution: '4K UHD (3840 x 2160)',
    refreshRate: '144Hz',
    panelType: 'IPS',
    price: 52990,
    priceDisplay: '₹52,990',
    availability: 'In Stock',
    badge: '4K 144Hz',
    image: 'assets/products/monitor-gaming.jpg',
    gallery: [
      'assets/products/monitor-gaming.jpg',
      'assets/products/monitor-office.jpg',
      'assets/products/monitor.jpg'
    ],
    shortSpecs: '27" 4K UHD • 144Hz • 1ms • HDMI 2.1 • Built-in KVM • aRGB Lighting',
    fullSpecs: {
      screenSize: '27.0 Inches Anti-Glare Micro-Edge IPS',
      resolution: '3840 x 2160 (4K UHD 16:9)',
      panelType: 'IPS with VESA DisplayHDR 400',
      refreshRate: '144Hz',
      responseTime: '1ms (with Overdrive)',
      brightness: '400 nits',
      colorGamut: '99% sRGB, 95% DCI-P3 Color Gamut',
      ports: '1x HDMI 2.1 (for PS5/Xbox Series X 4K 120Hz), 1x DisplayPort 1.4, 1x USB-C (Data/Display), 2x USB-A 3.2, Built-in KVM Switch, 3.5mm Audio',
      adaptiveSync: 'AMD FreeSync Premium Pro & G-Sync Compatible',
      standErgo: 'Height Adjustment (100mm) & Tilt (-5°~+20°), OMEN Light Studio RGB ambient glow',
      warranty: '3-Year HP Commercial Hardware Support'
    },
    description: 'The HP OMEN 27k is built for gamers who demand crystal-clear 4K visual detail without sacrificing high-frame-rate fluidity. Full HDMI 2.1 support allows native 4K 120Hz console gaming, while an onboard KVM switch lets you seamlessly toggle between your work laptop and gaming rig.',
    isDemo: true
  },
  {
    id: 'lenovo-legion-y27q',
    brand: 'Lenovo',
    model: 'Lenovo Legion Y27q-30 27" QHD 180Hz',
    tagline: 'Esports Tournament Ready 0.5ms MPRT Fast IPS Display',
    category: 'Gaming Monitor',
    screenSize: '27"',
    resolution: 'QHD (2560 x 1440)',
    refreshRate: '180Hz',
    panelType: 'Fast IPS',
    price: 27990,
    priceDisplay: '₹27,990',
    availability: 'In Stock',
    badge: '180Hz Fast IPS',
    image: 'assets/products/monitor-office.jpg',
    gallery: [
      'assets/products/monitor-office.jpg',
      'assets/products/monitor-gaming.jpg',
      'assets/products/monitor-dell.jpg'
    ],
    shortSpecs: '27" QHD • 180Hz (Overclocked) • 0.5ms MPRT • 99% sRGB, 95% DCI-P3 • Dual 3W Speakers',
    fullSpecs: {
      screenSize: '27.0 Inches 3-Side NearEdgeless IPS',
      resolution: '2560 x 1440 (QHD)',
      panelType: 'In-Plane Switching with VESA DisplayHDR 400',
      refreshRate: '165Hz Native / 180Hz Overclock Mode',
      responseTime: '0.5ms (MPRT) / 1ms (Level 4 Overdrive)',
      brightness: '400 nits',
      colorGamut: '99% sRGB, 95% DCI-P3, 10-Bit Color Depth (8+FRC)',
      ports: '2x HDMI 2.0, 1x DisplayPort 1.4, 4x USB 3.2 Gen 1 downstream Hub, 1x USB-B upstream, Dual 3W Stereo Speakers',
      adaptiveSync: 'AMD FreeSync Premium & VESA AdaptiveSync',
      standErgo: 'Ergonomic Stand with 135mm Lift, Tilt, Swivel, Pivot & Phone Cradle Base',
      warranty: '3-Year Lenovo Onsite Warranty'
    },
    description: 'Engineered for tournament esports titles like CS2, Valorant, and Apex Legends, the Lenovo Legion Y27q-30 combines an ultra-fast 180Hz refresh rate with a pinpoint 0.5ms MPRT response time. Its factory color calibration also ensures exceptional fidelity for video editing and content consumption.',
    isDemo: true
  },
  {
    id: 'acer-nitro-vg271u',
    brand: 'Acer',
    model: 'Acer Nitro VG271U M3 27" WQHD 180Hz',
    tagline: 'High-Value WQHD Gaming Monitor with 0.5ms Response & HDR10',
    category: 'Gaming Monitor',
    screenSize: '27"',
    resolution: 'WQHD (2560 x 1440)',
    refreshRate: '180Hz',
    panelType: 'Fast IPS',
    price: 18990,
    priceDisplay: '₹18,990',
    availability: 'In Stock',
    badge: 'Best Budget 1440p',
    image: 'assets/products/monitor-gaming.jpg',
    gallery: [
      'assets/products/monitor-gaming.jpg',
      'assets/products/monitor.jpg',
      'assets/products/monitor-curved.jpg'
    ],
    shortSpecs: '27" WQHD (2560x1440) • 180Hz • 0.5ms • 99% sRGB • Dual 2W Speakers • FreeSync',
    fullSpecs: {
      screenSize: '27.0 Inches ZeroFrame IPS Display',
      resolution: '2560 x 1440 (WQHD 16:9)',
      panelType: 'Agile-Splendor Fast IPS with HDR10',
      refreshRate: '180Hz Refresh Rate',
      responseTime: '0.5ms (Min. GTG)',
      brightness: '250 nits typical (HDR10 mode 300 nits)',
      colorGamut: '99% sRGB Color Accuracy',
      ports: '2x HDMI 2.0, 1x DisplayPort 1.2, Audio Out, Integrated 2W x 2 Stereo Speakers',
      adaptiveSync: 'AMD FreeSync Premium',
      standErgo: 'Tilt Angle (-5° to 20°), 100x100mm VESA Wall Mount Compatible',
      warranty: '3-Year Acer Onsite Warranty'
    },
    description: 'The Acer Nitro VG271U M3 delivers stunning 1440p resolution and a super-smooth 180Hz refresh rate at an unbeatable price point. Features Acer VisionCare technology to reduce eye fatigue during long sessions, plus built-in stereo speakers.',
    isDemo: true
  }
];

// Helper to look up a monitor by its ID
function getMonitorById(id) {
  return MONITOR_DATA.find(item => item.id === id) || null;
}
